name: 'Setup oneAPI'
description: 'Install oneAPI components'
inputs:
  components:
    description: 'Components to install'
    default: ''
  cache:
    description: 'Cache the install'
    default: true
  prune:
    description: 'Speed up save/restore by removing infrequently used files'
    default: true
  list:
    description: 'List the available components'
    default: false
runs:
  using: 'node16'
  main: 'dist/main/index.js'
  post: 'dist/cleanup/index.js'
