name: 'Setup oneAPI'
description: 'Install oneAPI components'
inputs:
  components:  
    description: 'Components to install'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'