on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    name: Install oneapi tools
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        list: true
        components: |
          tbb
          vpl
          icx
    - name: Test install
      run: |
        source /opt/intel/oneapi/setvars.sh
